<?php
/****
* This file contains a hard coded categorisation of components in the 
* linked data lifecycle. You need to add the name of the debian Package 
* in the category_package array in order to see the component in the website
*/

$categories = array(
	-1 => "Uncategorised",
	0 =>"Integreation Workbench",
	1 =>"Extraction and Loading",
	2 =>"Interlinking and Fusing",
	3 =>"Classification and Enrichment",
	4 =>"Quality Analysis",
	5 =>"Evolution and Repair",
	6 =>"Search, Browsing and Exploration",
	7 =>"Storage and Querying",
	8 =>"Manual revision and Authoring",
	9 =>"Dataset");

$categroy_package = array(
	"colanut" => array(-1),
	"d2r" => array(-1),
	"d2r-cordis" => array(-1),
	"dbpedia-spotlight-ui" => array(-1),
	"dl-learner-components-core" => array(-1),
	"dl-learner-interfaces" => array(-1),
	"facete" => array(-1),
	"geoknow-generator-ui" => array(-1),
	"geolift-service" => array(-1),
	"liberfurt-php" => array(-1),
	"libjs-rdfauthor" => array(-1),
	"libvirtodbc0" => array(-1),
	"libvirtuoso5.5-cil" => array(-1),
	"limes" => array(-1),
	"limes-service" => array(-1),
	"lod2-refine" => array(-1),
	"lod2-virtuoso-opensource" => array(-1),
	"lod2demo" => array(-1),
	"lod2statworkbench" => array(-1),
	"lod2virt7-repository" => array(-1),
	"lod2webapi" => array(-1),
	"lodgrefine" => array(-1),
	"lodms" => array(-1),
	"lodrefine" => array(-1),
	"marmotta" => array(-1),
	"olanut" => array(-1),
	"ontowiki-common" => array(-1),
	"ontowiki-csvimport" => array(-1),
	"ontowiki-cubeviz" => array(-1),
	"ontowiki-mysql" => array(-1),
	"ontowiki-virtuoso" => array(-1),
	"ore-gwt" => array(-1),
	"owcli" => array(-1),
	"rdf-dataset-integration" => array(-1),
	"rdf.sh" => array(-1),
	"sieve" => array(-1),
	"sigmaee" => array(-1),
	"silk" => array(-1),
	"silk-latc" => array(-1),
	"siren" => array(-1),
	"sparqled" => array(-1),
	"sparqlify" => array(-1),
	"sparqlproxy-php" => array(-1),
	"spatial-semantic-browser" => array(-1),
	"stanbol" => array(-1),
	"triplegeo" => array(-1),
	"triplegeo-service" => array(-1),
	"virtuoso-minimal" => array(-1),
	"virtuoso-nepomuk" => array(-1),
	"virtuoso-opensource-7.0" => array(-1),
	"virtuoso-opensource-7.0-bin" => array(-1),
	"virtuoso-opensource-7.0-common" => array(-1),
	"virtuoso-server" => array(-1),
	"virtuoso-vad-bpel" => array(-1),
	"virtuoso-vad-conductor" => array(-1),
	"virtuoso-vad-demo" => array(-1),
	"virtuoso-vad-doc" => array(-1),
	"virtuoso-vad-isparql" => array(-1),
	"virtuoso-vad-ods" => array(-1),
	"virtuoso-vad-rdfmappers" => array(-1),
	"virtuoso-vad-sparqldemo" => array(-1),
	"virtuoso-vsp-startpage" => array(-1),
	"virtuoso-vad-syncml" => array(-1),
	"virtuoso-vad-tutorial" => array(-1) );
?>
